chapters_en = {
    1: {
        "1": "The proverbs of Solomon son of David, king of Israel:",
        "2": "For learning wisdom and discipline;\nFor understanding words of discernment;",
        "3": "For acquiring the discipline for success,\nRighteousness, justice, and equity;",
        "4": "For endowing the simple with shrewdness,\nThe young with knowledge and foresight.",
        "5": "The wise man, hearing them, will gain more wisdom;\nThe discerning man will learn to be adroit;",
        "6": "For understanding proverb and epigram,\nThe words of the wise and their riddles.",
        "7": "The fear of the LORD is the beginning of knowledge;\nFools despise wisdom and discipline.",
        "8": "My son, heed the discipline of your father,\nAnd do not forsake the instruction of your mother;",
        "9": "For they are a graceful wreath upon your head,\nA necklace about your throat.",
        "10": "My son, if sinners entice you, do not yield;",
        "11": "If they say, \"Come with us,\nLet us set an ambush to shed blood,\nLet us lie in wait for the innocent\n(Without cause!)\"",
        "12": "Like Sheol, let us swallow them alive;\nWhole, like those who go down into the Pit.",
        "13": "We shall obtain every precious treasure;\nWe shall fill our homes with loot.",
        "14": "Throw in your lot with us;\nWe shall all have a common purse.",
        "15": "My son, do not set out with them;\nKeep your feet from their path.",
        "16": "For their feet run to evil;\nThey hurry to shed blood.",
        "17": "In the eyes of every winged creature\nThe outspread net means nothing.",
        "18": "But they lie in ambush for their own blood;\nThey lie in wait for their own lives.",
        "19": "Such is the fate of all who pursue unjust gain;\nIt takes the life of its possessor.",
        "20": "Wisdom cries aloud in the streets,\nRaises her voice in the squares.",
        "21": "At the head of the busy streets she calls;\nAt the entrance of the gates, in the city, she speaks out:",
        "22": "\"How long will you simple ones love simplicity,\nYou scoffers be eager to scoff,\nYou dullards hate knowledge?\"",
        "23": "You are indifferent to my rebuke;\nI will now speak my mind to you,\nAnd let you know my thoughts.",
        "24": "Since you refused me when I called,\nAnd paid no heed when I extended my hand,",
        "25": "You spurned all my advice,\nAnd would not hear my rebuke,",
        "26": "I will laugh at your calamity,\nAnd mock when terror comes upon you,",
        "27": "When terror comes like a disaster,\nAnd calamity arrives like a whirlwind,\nWhen trouble and distress come upon you.",
        "28": "Then they shall call me but I will not answer;\nThey shall seek me but not find me.",
        "29": "Because they hated knowledge,\nAnd did not choose fear of the LORD;",
        "30": "They refused my advice,\nAnd disdained all my rebukes,",
        "31": "They shall eat the fruit of their ways,\nAnd have their fill of their own counsels.",
        "32": "The tranquillity of the simple will kill them,\nAnd the complacency of dullards will destroy them.",
        "33": "But he who listens to me will dwell in safety,\nUntroubled by the terror of misfortune."
    },
    2: {
        "1": "My son, if you accept my words\nAnd treasure up my commandments;",
        "2": "If you make your ear attentive to wisdom\nAnd your mind open to discernment;",
        "3": "If you call to understanding\nAnd cry aloud to discernment,",
        "4": "If you seek it as you do silver\nAnd search for it as for treasures,",
        "5": "Then you will understand the fear of the LORD\nAnd attain knowledge of God.",
        "6": "For the LORD grants wisdom;\nKnowledge and discernment are by His decree.",
        "7": "He reserves ability for the upright\nAnd is a shield for those who live blamelessly,",
        "8": "Guarding the paths of justice,\nProtecting the way of those loyal to Him.",
        "9": "You will then understand what is right, just,\nAnd equitable—every good course.",
        "10": "For wisdom will enter your mind\nAnd knowledge will delight you.",
        "11": "Foresight will protect you,\nAnd discernment will guard you.",
        "12": "It will save you from the way of evil men,\nFrom men who speak duplicity,",
        "13": "Who leave the paths of rectitude\nTo follow the ways of darkness,",
        "14": "Who rejoice in doing evil\nAnd exult in the duplicity of evil men,",
        "15": "Men whose paths are crooked\nAnd who are devious in their course.",
        "16": "It will save you from the forbidden woman,\nFrom the alien woman whose talk is smooth,",
        "17": "Who forsakes the companion of her youth\nAnd disregards the covenant of her God.",
        "18": "Her house sinks down to Death,\nAnd her course leads to the shades.",
        "19": "All who go to her cannot return\nAnd find again the paths of life.",
        "20": "So follow the way of the good\nAnd keep to the paths of the just.",
        "21": "For the upright will inhabit the earth,\nThe blameless will remain in it.",
        "22": "While the wicked will vanish from the land\nAnd the treacherous will be rooted out of it."
    },
    3: {
        "1": "My son, do not forget my teaching,\nBut let your mind retain my commandments;",
        "2": "For they will bestow on you length of days,\nYears of life and well-being.",
        "3": "Let fidelity and steadfastness not leave you;\nBind them about your throat,\nWrite them on the tablet of your mind,",
        "4": "And you will find favor and approbation\nIn the eyes of God and man.",
        "5": "Trust in the LORD with all your heart,\nAnd do not rely on your own understanding.",
        "6": "In all your ways acknowledge Him,\nAnd He will make your paths smooth.",
        "7": "Do not be wise in your own eyes;\nFear the LORD and shun evil.",
        "8": "It will be a cure for your body,\nA tonic for your bones.",
        "9": "Honor the LORD with your wealth,\nWith the best of all your income,",
        "10": "And your barns will be filled with grain,\nYour vats will burst with new wine.",
        "11": "Do not reject the discipline of the LORD, my son;\nDo not abhor His rebuke.",
        "12": "For whom the LORD loves, He rebukes,\nAs a father the son whom he favors.",
        "13": "Happy is the man who finds wisdom,\nThe man who attains understanding.",
        "14": "Her value in trade is better than silver,\nHer yield, greater than gold.",
        "15": "She is more precious than rubies;\nAll of your goods cannot equal her.",
        "16": "In her right hand is length of days,\nIn her left, riches and honor.",
        "17": "Her ways are pleasant ways,\nAnd all her paths, peaceful.",
        "18": "She is a tree of life to those who grasp her,\nAnd whoever holds on to her is happy.",
        "19": "The LORD founded the earth by wisdom;\nHe established the heavens by understanding;",
        "20": "By His knowledge the depths burst apart,\nAnd the skies distilled dew.",
        "21": "My son, do not lose sight of them;\nHold on to resourcefulness and foresight.",
        "22": "They will give life to your spirit\nAnd grace to your throat.",
        "23": "Then you will go your way safely\nAnd not injure your feet.",
        "24": "When you lie down you will be unafraid;\nYou will lie down and your sleep will be sweet.",
        "25": "You will not fear sudden terror\nOr the disaster that comes upon the wicked,",
        "26": "For the LORD will be your trust;\nHe will keep your feet from being caught.",
        "27": "Do not withhold good from one who deserves it\nWhen you have the power to do it [for him].",
        "28": "Do not say to your fellow, \"Come back again;\nI'll give it to you tomorrow,\" when you have it with you.",
        "29": "Do not devise harm against your fellow\nWho lives trustfully with you.",
        "30": "Do not quarrel with a man for no cause,\nWhen he has done you no harm.",
        "31": "Do not envy a lawless man,\nOr choose any of his ways;",
        "32": "For the devious man is an abomination to the LORD,\nBut He is intimate with the straightforward.",
        "33": "The curse of the LORD is on the house of the wicked,\nBut He blesses the abode of the righteous.",
        "34": "At scoffers He scoffs,\nBut to the lowly He shows grace.",
        "35": "The wise shall obtain honor,\nBut dullards get disgrace as their portion."
    },
    4: {
        "1": "Sons, heed the discipline of a father; Listen and learn discernment,",
        "2": "For I give you good instruction; Do not forsake my teaching.",
        "3": "Once I was a son to my father, The tender darling of my mother.",
        "4": "He instructed me and said to me, 'Let your mind hold on to my words; Keep my commandments and you will live.",
        "5": "Acquire wisdom, acquire discernment; Do not forget and do not swerve from my words.",
        "6": "Do not forsake her and she will guard you; Love her and she will protect you.",
        "7": "The beginning of wisdom is—acquire wisdom; With all your acquisitions, acquire discernment.",
        "8": "Hug her to you and she will exalt you; She will bring you honor if you embrace her.",
        "9": "She will adorn your head with a graceful wreath; Crown you with a glorious diadem.'",
        "10": "My son, heed and take in my words, And you will have many years of life.",
        "11": "I instruct you in the way of wisdom; I guide you in straight courses.",
        "12": "You will walk without breaking stride; When you run, you will not stumble.",
        "13": "Hold fast to discipline; do not let go; Keep it; it is your life.",
        "14": "Do not enter on the path of the wicked; Do not walk on the way of evildoers.",
        "15": "Avoid it; do not pass through it; Turn away from it; pass it by.",
        "16": "For they cannot sleep unless they have done evil; Unless they make someone fall they are robbed of sleep.",
        "17": "They eat the bread of wickedness And drink the wine of lawlessness.",
        "18": "The path of the righteous is like radiant sunlight, Ever brightening until noon.",
        "19": "The way of the wicked is all darkness; They do not know what will make them stumble.",
        "20": "My son, listen to my speech; Incline your ear to my words.",
        "21": "Do not lose sight of them; Keep them in your mind.",
        "22": "They are life to those who find them, Healing for the whole body.",
        "23": "More than all that you guard, guard your mind, For it is the source of life.",
        "24": "Put crooked speech away from you; Keep devious talk far from you.",
        "25": "Let your eyes look forward, Your gaze be straight ahead.",
        "26": "Survey the course you take, And all your ways will prosper.",
        "27": "Do not swerve to the right or the left; Keep your feet from evil."
    },
    5: {
        "1": "My son, listen to my wisdom; Incline your ear to my insight,",
        "2": "That you may have foresight, While your lips hold fast to knowledge.",
        "3": "For the lips of a forbidden woman drip honey; Her mouth is smoother than oil;",
        "4": "But in the end she is as bitter as wormwood, Sharp as a two-edged sword.",
        "5": "Her feet go down to Death; Her steps take hold of Sheol.",
        "6": "She does not chart a path of life; Her course meanders for lack of knowledge.",
        "7": "So now, sons, pay heed to me, And do not swerve from the words of my mouth.",
        "8": "Keep yourself far away from her; Do not come near the doorway of her house",
        "9": "Lest you give up your vigor to others, Your years to a ruthless one;",
        "10": "Lest strangers eat their fill of your strength, And your toil be for the house of another;",
        "11": "And in the end you roar, When your flesh and body are consumed,",
        "12": "And say, 'O how I hated discipline, And heartily spurned rebuke.",
        "13": "I did not pay heed to my teachers, Or incline my ear to my instructors.",
        "14": "Soon I was in dire trouble Amidst the assembled congregation.'",
        "15": "Drink water from your own cistern, Running water from your own well.",
        "16": "Your springs will gush forth In streams in the public squares.",
        "17": "They will be yours alone, Others having no part with you.",
        "18": "Let your fountain be blessed: Find joy in the wife of your youth—",
        "19": "A loving doe, a graceful mountain goat. Let her breasts satisfy you at all times; Be infatuated with love of her always.",
        "20": "Why be infatuated, my son, with a forbidden woman? Why clasp the bosom of an alien woman?",
        "21": "For everyone’s ways are before the eyes of God, Who surveys their entire course.",
        "22": "The wicked man will be trapped in his iniquities; He will be caught up in the ropes of his sin.",
        "23": "He will die for lack of discipline, Infatuated by his great folly."
    },
    6: {
        "1": "My son, if you have stood surety for your fellow, Given your hand for another,",
        "2": "You have been trapped by the words of your mouth, Snared by the words of your mouth.",
        "3": "Do this, then, my son, to extricate yourself, For you have come into the power of your fellow: Go grovel—and badger your fellow;",
        "4": "Give your eyes no sleep, Your pupils no slumber.",
        "5": "Save yourself like a deer out of the hand [of a hunter], Like a bird out of the hand of a fowler.",
        "6": "Lazybones, go to the ant; Study its ways and learn.",
        "7": "Without leaders, officers, or rulers,",
        "8": "It lays up its stores during the summer, Gathers in its food at the harvest.",
        "9": "How long will you lie there, lazybones; When will you wake from your sleep?",
        "10": "A bit more sleep, a bit more slumber, A bit more hugging yourself in bed,",
        "11": "And poverty will come calling upon you, And want, like a man with a shield.",
        "12": "A scoundrel, an evil man Lives by crooked speech,",
        "13": "Winking his eyes, Shuffling his feet, Pointing his finger.",
        "14": "Duplicity is in his heart; He plots evil all the time; He incites quarrels.",
        "15": "Therefore calamity will come upon him without warning; Suddenly he will be broken beyond repair.",
        "16": "GOD hates six things— And abominates seven:",
        "17": "A haughty bearing, A lying tongue, Hands that shed innocent blood,",
        "18": "A mind that hatches evil plots, Feet quick to run to evil,",
        "19": "A false witness testifying lies, And one who incites siblings to quarrel.",
        "20": "My son, keep your father’s commandment; Do not forsake your mother’s teaching.",
        "21": "Tie them over your heart always; Bind them around your throat.",
        "22": "When you walk it will lead you; When you lie down it will watch over you; And when you are awake it will talk with you.",
        "23": "For the commandment is a lamp, The teaching is a light, And the way to life is the rebuke that disciplines.",
        "24": "It will keep you from an evil woman, From the smooth tongue of a forbidden woman.",
        "25": "Do not lust for her beauty Or let her captivate you with her eyes.",
        "26": "The last loaf of bread will go for a prostitute; A married woman will snare a person of honor.",
        "27": "Can anyone rake embers into their bosom Without burning their clothes?",
        "28": "Can anyone walk on live coals Without scorching their feet?",
        "29": "It is the same with the man who sleeps with his fellow’s wife; No one who touches her will go unpunished.",
        "30": "A thief is not held in contempt For stealing to appease his hunger;",
        "31": "Yet if caught he must pay sevenfold; He must give up all he owns.",
        "32": "He who commits adultery is devoid of sense; Only one who would destroy himself does such a thing.",
        "33": "He will meet with disease and disgrace; His reproach will never be expunged.",
        "34": "The fury of the husband will be passionate; He will show no pity on his day of vengeance.",
        "35": "He will not have regard for any ransom; He will refuse your bribe, however great."
    },
    7: {
        "1": "My son, heed my words; And store up my commandments with you.",
        "2": "Keep my commandments and live, My teaching, as the apple of your eye—",
        "3": "Bind them on your fingers, Write them on the tablet of your mind.",
        "4": "Say to Wisdom, 'You are my sister,' And call Understanding a kinswoman.",
        "5": "She will guard you from a forbidden woman; From an alien woman whose talk is smooth.",
        "6": "From the window of my house, Through my lattice, I looked out",
        "7": "And saw among the simple, Noticed among the youths, A young man devoid of sense.",
        "8": "He was crossing the street near her corner, Walking toward her house",
        "9": "In the dusk of evening, In the dark hours of night.",
        "10": "A woman comes toward him Dressed like a streetwalker, with set purpose.",
        "11": "She is bustling and restive; She is never at home.",
        "12": "Now in the street, now in the square, She lurks at every corner.",
        "13": "She lays hold of him and kisses him. Brazenly she says to him,",
        "14": "'I had to make a sacrifice of well-being; Today I fulfilled my vows.",
        "15": "Therefore I have come out to you, Seeking you, and have found you.",
        "16": "I have decked my couch with covers Of dyed Egyptian linen;",
        "17": "I have sprinkled my bed With myrrh, aloes, and cinnamon.",
        "18": "Let us drink our fill of love till morning; Let us delight in amorous embrace.",
        "19": "For the man of the house is away; He is off on a distant journey.",
        "20": "He took his bag of money with him And will return only at mid-month.'",
        "21": "She sways him with her eloquence, Turns him aside with her smooth talk.",
        "22": "Thoughtlessly he follows her, Like an ox going to the slaughter, Like a fool to the stocks for punishment—",
        "23": "Until the arrow pierces his liver. He is like a bird rushing into a trap, Not knowing his life is at stake.",
        "24": "Now, sons, listen to me; Pay attention to my words;",
        "25": "Let your mind not wander down her ways; Do not stray onto her paths.",
        "26": "For many are those she has struck dead, And numerous are her victims.",
        "27": "Her house is a highway to Sheol Leading down to Death’s inner chambers."
    },
    8: {
        "1": "It is Wisdom calling, Understanding raising her voice.",
        "2": "She takes her stand at the topmost heights, By the wayside, at the crossroads,",
        "3": "Near the gates at the city entrance; At the entryways, she shouts,",
        "4": "'O human race, I call to you; My cry is to all mortals.",
        "5": "O simple ones, learn shrewdness; O dullards, instruct your minds.",
        "6": "Listen, for I speak noble things; Uprightness comes from my lips.",
        "7": "My mouth utters truth; Wickedness is abhorrent to my lips.",
        "8": "All my words are just, None of them perverse or crooked;",
        "9": "All are straightforward to anyone with intelligence, And right to those who have attained knowledge.",
        "10": "Accept my discipline rather than silver, Knowledge rather than choice gold.",
        "11": "For wisdom is better than rubies; No goods can equal her.",
        "12": "'I, Wisdom, live with Prudence; I attain knowledge and foresight.",
        "13": "To fear God is to hate evil; I hate pride, arrogance, the evil way, And duplicity in speech.",
        "14": "Mine are counsel and resourcefulness; I am understanding; courage is mine.",
        "15": "Through me kings reign And rulers decree just laws;",
        "16": "Through me princes rule, Great men and all the righteous judges.",
        "17": "Those who love me I love, And those who seek me will find me.",
        "18": "Riches and honor belong to me, Enduring wealth and success.",
        "19": "My fruit is better than gold, fine gold, And my produce better than choice silver.",
        "20": "I walk on the way of righteousness, On the paths of justice.",
        "21": "I endow those who love me with substance; I will fill their treasuries.",
        "22": "'I was created at the beginning of God’s course As the first of the works of old.",
        "23": "In the distant past I was fashioned, At the beginning, at the origin of earth.",
        "24": "There was still no deep when I was brought forth, No springs rich in water;",
        "25": "Before [the foundations of] the mountains were sunk, Before the hills I was born.",
        "26": "Earth and fields had not yet been made, Or the world’s first clumps of clay.",
        "27": "I was there when the heavens were set into place; When the horizon was fixed upon the deep;",
        "28": "When the heavens above were made firm, And the fountains of the deep gushed forth;",
        "29": "When the sea was assigned its limits, So that its waters never transgress God’s command; When the foundations of the earth were fixed,",
        "30": "I was with [God] as a confidant, A source of delight every day, Rejoicing before [God] at all times,",
        "31": "Rejoicing in God’s inhabited world, Finding delight with mortals.",
        "32": "Now, children, listen to me; Happy are they who keep my ways.",
        "33": "Heed discipline and become wise; Do not spurn it.",
        "34": "Happy is the one who listens to me, Coming early to my gates each day, Waiting outside my doors.",
        "35": "For one who finds me finds life And obtains favor from God.",
        "36": "But one who misses me self-destructs; All who hate me love death.'"
    },
    9: {
        "1": "Wisdom has built her house, She has hewn her seven pillars.",
        "2": "She has prepared the feast, Mixed the wine, And also set the table.",
        "3": "She has sent out her maids to announce On the heights of the town,",
        "4": "'Let the simple enter here.' To those devoid of sense she says,",
        "5": "'Come, eat my food And drink the wine that I have mixed;",
        "6": "Give up simpleness and live, Walk in the way of understanding.'",
        "7": "To correct a scoffer, Or rebuke an evildoer regarding a blemish, Is to call down abuse on oneself.",
        "8": "Do not rebuke scoffers, for they will hate you; Reprove the wise, and they will love you.",
        "9": "Instruct the wise, and they will grow wiser; Teach the righteous, and they will gain in learning.",
        "10": "The beginning of wisdom is fear of God, And knowledge of the Holy One is understanding.",
        "11": "For through me your days will increase, And years be added to your life.",
        "12": "If you are wise, you are wise for yourself; If you are a scoffer, you bear it alone.",
        "13": "The stupid woman bustles about; She is simple and knows nothing.",
        "14": "She sits in the doorway of her house, Or on a chair at the heights of the town,",
        "15": "Calling to all the wayfarers Who go about their own affairs,",
        "16": "'Let the simple enter here'; And to those devoid of sense she says,",
        "17": "'Stolen waters are sweet, And bread eaten furtively is tasty.'",
        "18": "He does not know that the shades are there, That her guests are in the depths of Sheol."
    },
    10: {
        "1": "The proverbs of Solomon: A wise son brings joy to his father; A dull son is his mother’s sorrow.",
        "2": "Ill-gotten wealth is of no avail, But righteousness saves from death.",
        "3": "God will not let a righteous person go hungry, But denies the wicked what they crave.",
        "4": "Negligent hands cause poverty, But diligent hands enrich.",
        "5": "He who lays in stores during the summer is a capable son, But he who sleeps during the harvest is an incompetent.",
        "6": "Blessings light upon the head of a righteous person, But lawlessness covers the mouths of the wicked.",
        "7": "The name of a righteous person is invoked in blessing, But the fame of the wicked rots.",
        "8": "Whoever has a wise heart accepts commands, But one whose speech is foolish comes to grief.",
        "9": "Whoever lives blamelessly lives safely, But one who walks a crooked path will be found out.",
        "10": "Whoever winks causes sorrow; One whose speech is foolish comes to grief.",
        "11": "The mouth of a righteous person is a fountain of life, But lawlessness covers the mouths of the wicked.",
        "12": "Hatred stirs up strife, But love covers up all faults.",
        "13": "Wisdom is to be found on the lips of the intelligent, But a rod is ready for the back of the senseless.",
        "14": "The wise store up knowledge; The mouth of a fool is an imminent ruin.",
        "15": "For someone rich, wealth is a fortress; For the poor, poverty is a ruin.",
        "16": "The labor of the righteous makes for life; The produce of the wicked makes for want.",
        "17": "One who follows discipline shows the way to life, But one who ignores reproof leads astray.",
        "18": "One who conceals hatred has lying lips, While one who speaks forth slander is a dullard.",
        "19": "Where there is much talking, there is no lack of transgressing, But one who curbs the tongue shows sense.",
        "20": "The tongue of a righteous person is choice silver, But the mind of the wicked is of little worth.",
        "21": "The lips of a righteous person sustain many, But fools die for lack of sense.",
        "22": "It is the blessing of God that enriches, And no toil can increase it.",
        "23": "As mischief is sport for the dullard, So is wisdom for the man of understanding.",
        "24": "What an evildoer plots backfires; What the righteous desire is granted.",
        "25": "When the storm passes a wicked person is gone, But the righteous person is an everlasting foundation.",
        "26": "Like vinegar to the teeth, Like smoke to the eyes, Are sluggards to those who send them on a mission.",
        "27": "The fear of God prolongs life, While the years of the wicked will be shortened.",
        "28": "The righteous can look forward to joy, But the hopes of the wicked are doomed.",
        "29": "The way of God is a stronghold for a blameless person, But a ruin for evildoers.",
        "30": "The righteous person will never be shaken; The wicked will not inhabit the earth.",
        "31": "The mouth of a righteous person produces wisdom, But the treacherous tongue shall be cut off.",
        "32": "The lips of a righteous person know what is pleasing; The mouth of the wicked [knows] duplicity."
    },
    11: {
        "1": "False scales are an abomination to God, Who finds an honest weight pleasing.",
        "2": "When arrogance appears, disgrace follows, But wisdom is with those who are unassuming.",
        "3": "The integrity of the upright guides them; The deviousness of the treacherous leads them to ruin.",
        "4": "Wealth is of no avail on the day of wrath, But righteousness saves from death.",
        "5": "The righteousness of the blameless smooths their way, But the wicked fall by their wickedness.",
        "6": "The righteousness of the upright saves them, But the treacherous are trapped by their malice.",
        "7": "At death the hopes of a wicked person are doomed, And the ambition of evildoers comes to nothing.",
        "8": "A righteous person is rescued from trouble And it comes to the wicked instead.",
        "9": "An impious person destroys a neighbor through speech, But through knowledge the righteous are rescued.",
        "10": "When the righteous prosper the city exults; When the wicked perish there are shouts of joy.",
        "11": "A city is built up by the blessing of the upright, But it is torn down by the speech of the wicked.",
        "12": "One who speaks contemptuously of neighbors is devoid of sense; A prudent man keeps his peace.",
        "13": "A base fellow gives away secrets, But a trustworthy soul keeps a confidence.",
        "14": "For want of strategy an army falls, But victory comes with much planning.",
        "15": "Harm awaits one who stands surety for another; One who spurns pledging shall be secure.",
        "16": "A graceful woman obtains honor; Ruthless men obtain wealth.",
        "17": "A kindly man benefits himself; A cruel one makes trouble for himself.",
        "18": "A wicked person earns illusory wages, But one who sows righteousness has a true reward.",
        "19": "Righteousness is a prop of life, But to pursue evil leads to death.",
        "20": "Crooked minds are an abomination to God, But those whose way is blameless are pleasing.",
        "21": "Assuredly, the evildoer will not escape, But the offspring of the righteous will be safe.",
        "22": "Like a gold ring in the snout of a pig Is a beautiful woman bereft of sense.",
        "23": "What the righteous desire can only be good; What the wicked hope for [stirs] wrath.",
        "24": "Some give generously and end with more; Others stint on doing the right thing and incur a loss.",
        "25": "A generous person enjoys prosperity; One who satisfies others shall likewise be sated.",
        "26": "Whoever withholds grain earns the curses of the people, But blessings are on the head of the one who dispenses it.",
        "27": "One who earnestly seeks good pursues what is pleasing; Evil comes to someone who is bent on it.",
        "28": "One who trusts in wealth shall fall, But the righteous shall flourish like foliage.",
        "29": "He who makes trouble for his household shall inherit the wind; A fool is a slave to the wise-hearted.",
        "30": "The fruit of the righteous is a tree of life; The wise captivate people.",
        "31": "If the righteous on earth get their deserts, How much more evildoers and sinners."
    },
    12: {
        "1": "One who loves discipline loves knowledge; Whoever spurns reproof is a brute.",
        "2": "A good person earns the favor of God, A man of intrigues, God’s condemnation.",
        "3": "No one can be established in wickedness, But the root of the righteous will not be shaken loose.",
        "4": "A woman of substance is a crown for her husband, But an incompetent one is like rot in his bones.",
        "5": "The purposes of the righteous are justice, The schemes of the wicked are deceit.",
        "6": "The words of the wicked are a deadly ambush, But the speech of the upright saves them.",
        "7": "Overturn the wicked and they are gone, But the house of the righteous will endure.",
        "8": "A man is commended according to his intelligence; A twisted mind is held up to contempt.",
        "9": "Better to be lightly esteemed and have a servant Than to put on airs and have no food.",
        "10": "A righteous person knows the needs of their beast, But the compassion of the wicked is cruelty.",
        "11": "He who tills his land shall have food in plenty, But one who pursues vanities is devoid of sense.",
        "12": "A wicked man covets the catch of evildoers; The root of the righteous yields fruit.",
        "13": "Sinful speech is a trap for the evildoer, But a righteous man escapes from trouble.",
        "14": "A man gets his fill of good from the fruit of his speech; One is repaid in kind for one’s deeds.",
        "15": "The way of fools is right in their own eyes; But those who are wise accept advice.",
        "16": "Fools’ vexation is known at once, But the clever conceal their humiliation.",
        "17": "A faithful witness tells the truth, But a false witness, deceit.",
        "18": "There is blunt talk like sword-thrusts, But the speech of the wise is healing.",
        "19": "Truthful speech abides forever, A lying tongue for but a moment.",
        "20": "Deceit is in the minds of those who plot evil; For those who plan good there is joy.",
        "21": "No harm befalls a righteous person, But the wicked have their fill of misfortune.",
        "22": "Lying speech is an abomination to God, But those who act faithfully are pleasing.",
        "23": "A clever person conceals knowledge, But the mind of dullards cries out folly.",
        "24": "The hand of the diligent wields authority; The negligent are held in subjection.",
        "25": "If there is anxiety in someone’s mind, let them quash it, And turn it into joy with a good word.",
        "26": "A righteous person gives friends direction, But the way of the wicked leads astray.",
        "27": "A negligent person never has game to roast; A diligent one has precious wealth.",
        "28": "The road of righteousness leads to life; By way of its path there is no death."
    },
    13: {
        "1": "A wise son—it is through the discipline of his father; A scoffer—he never heard reproof.",
        "2": "A man enjoys good from the fruit of his speech; But out of the throat of the treacherous comes lawlessness.",
        "3": "Those who guard their tongue preserve their life; Those who open wide their lips, it is their ruin.",
        "4": "A sluggard craves, but has nothing; The diligent shall feast on rich fare.",
        "5": "The righteous hate lies; The wicked are vile and disgraceful.",
        "6": "Righteousness protects the one whose way is blameless; Wickedness subverts the sinner.",
        "7": "Some pretend to be rich and have nothing; Others profess to be poor and have much wealth.",
        "8": "Riches are ransom for a person’s life, The poor never heard a reproof.",
        "9": "The light of the righteous is radiant; The lamp of the wicked is extinguished.",
        "10": "Arrogance yields nothing but strife; Wisdom belongs to those who seek advice.",
        "11": "Wealth may dwindle to less than nothing, But one who gathers little by little increases it.",
        "12": "Hope deferred sickens the heart, But desire realized is a tree of life.",
        "13": "One who disdains a precept will be injured thereby; One who respects a command will be rewarded.",
        "14": "The instruction of the wise is a fountain of life, Enabling one to avoid deadly snares.",
        "15": "Good sense wins favor; The way of treacherous men is unchanging.",
        "16": "Those who are clever act knowledgeably, But dullards expose their stupidity.",
        "17": "Harm befalls a wicked messenger; A faithful courier brings healing.",
        "18": "Poverty and humiliation are for the one who spurns discipline; But one who takes reproof to heart gets honor.",
        "19": "Desire realized is sweet to the soul; To turn away from evil is abhorrent to the stupid.",
        "20": "One who keeps company with the wise becomes wise, But one who consorts with dullards comes to grief.",
        "21": "Misfortune pursues sinners, But the righteous are well rewarded.",
        "22": "A good man has what to bequeath to his grandchildren, For the wealth of sinners is stored up for the righteous.",
        "23": "The tillage of the poor yields much food; But substance is swept away for lack of moderation.",
        "24": "He who spares the rod hates his son, But he who loves him disciplines him early.",
        "25": "The righteous person eats to satiety, But the belly of the wicked is empty."
    },
    14: {
        "1": "The wisest of women builds her house, But folly tears it down with its own hands.",
        "2": "One who walks a straight path fears God; But one whose ways are devious shows scorn.",
        "3": "In the mouth of a fool is a rod of haughtiness, But the lips of the wise protect them.",
        "4": "If there are no oxen the crib is clean, But a rich harvest comes through the strength of the ox.",
        "5": "An honest witness will not lie; A false witness testifies lies.",
        "6": "Scoffers seek wisdom in vain, But knowledge comes easily to the intelligent.",
        "7": "Keep your distance from a dull man, For you will not learn wise speech.",
        "8": "It is the wisdom of a clever man to understand his course; But the stupidity of dullards is delusion.",
        "9": "Reparations mediate between fools, Between the upright, good will.",
        "10": "The heart alone knows its bitterness, And no outsider can share in its joy.",
        "11": "The house of the wicked will be demolished, But the tent of the upright will flourish.",
        "12": "The road ahead may seem right, But in the end it can be a road to death.",
        "13": "The heart may ache even in laughter, And joy may end in grief.",
        "14": "Those who are unprincipled reap the fruits of their ways; The good man, of his deeds.",
        "15": "The simple believe anything; The clever ponders their course.",
        "16": "A sage is diffident and shuns evil, But a dullard rushes in confidently.",
        "17": "A hothead commits folly; A man of intrigues will be hated.",
        "18": "Folly is the lot of the simple, But the clever glory in knowledge.",
        "19": "Evildoers are brought low before the good, So are the wicked at the gates of the righteous.",
        "20": "The poor are despised even by their peers, But the rich have many friends.",
        "21": "Those who despise their fellows are wrong; Those who show pity for the lowly are happy.",
        "22": "Surely those who plan evil go astray, While those who plan good earn steadfast love.",
        "23": "From all toil there is some gain, But idle chatter is pure loss.",
        "24": "The ornament of the wise is their wealth; The stupidity of dullards is stupidity.",
        "25": "A truthful witness saves lives; A lying witness spreads deceit.",
        "26": "Fear of God is a stronghold, A refuge for one’s children.",
        "27": "Fear of God is a fountain of life, Enabling one to avoid deadly snares.",
        "28": "A numerous people is the glory of a king; Without a nation a ruler is ruined.",
        "29": "Patience results in much understanding; Impatience gets folly as its portion.",
        "30": "A calm disposition gives bodily health; Passion is rot to the bones.",
        "31": "One who withholds what is due to the poor affronts their Maker; One who shows pity for the needy shows honor.",
        "32": "The wicked fall by their own evil; The righteous find security in their death.",
        "33": "Wisdom rests quietly in the mind of a prudent person, But among dullards it makes itself known.",
        "34": "Righteousness exalts a nation; Sin is a reproach to any people.",
        "35": "The king favors a capable servant; He rages at an incompetent one."
    },
    15: {
        "1": "A gentle response allays wrath; A harsh word provokes anger.",
        "2": "The tongue of the wise produces much knowledge, But the mouth of dullards pours out folly.",
        "3": "God’s eyes are everywhere, Observing the bad and the good.",
        "4": "A healing tongue is a tree of life, But a devious one makes for a broken spirit.",
        "5": "A fool spurns a parent’s discipline, But one who heeds reproof becomes clever.",
        "6": "In the house of the righteous there is much treasure, But in the harvest of the wicked there is trouble.",
        "7": "The lips of the wise disseminate knowledge; Not so the minds of dullards.",
        "8": "The sacrifice of the wicked is an abomination to God, But the prayer of the upright is pleasing.",
        "9": "The way of the wicked is an abomination to God, But those who pursue righteousness are loved.",
        "10": "Discipline seems bad to whoever forsakes the way; One who spurns reproof will die.",
        "11": "Sheol and Abaddon lie exposed to God, How much more the minds of mortals!",
        "12": "The scoffer, who dislikes being reproved, Will not resort to the wise.",
        "13": "A joyful heart makes a cheerful face; A sad heart makes a despondent mood.",
        "14": "The mind of a prudent person seeks knowledge; The mouth of dullards pursues folly.",
        "15": "All the days of a pauper are wretched, But contentment is a feast without end.",
        "16": "Better a little with fear of God Than great wealth with confusion.",
        "17": "Better a meal of vegetables where there is love Than a fattened ox where there is hate.",
        "18": "A hot-tempered man provokes a quarrel; A patient person calms strife.",
        "19": "The way of a sluggard is like a hedge of thorns, But the path of the upright is paved.",
        "20": "A wise son makes his father happy; A fool of a man humiliates his mother.",
        "21": "Folly is joy to one devoid of sense; A prudent man walks a straight path.",
        "22": "Plans are foiled for want of counsel, But they succeed through many advisers.",
        "23": "Having a ready response feels satisfying, And how good is a word rightly timed!",
        "24": "For the intelligent the path of life leads upward, In order to avoid Sheol below.",
        "25": "God will tear down the house of the proud— But will establish the homestead of the widow.",
        "26": "Evil thoughts are an abomination to God, But pleasant words are pure.",
        "27": "Whoever pursues ill-gotten gain makes trouble for the household; One who spurns gifts will live long.",
        "28": "A righteous person’s heart rehearses the answer, But the mouth of the wicked blurts out evil things.",
        "29": "God is far from the wicked— But hears the prayer of the righteous.",
        "30": "What brightens the eye gladdens the heart; Good news puts fat on the bones.",
        "31": "One whose ear heeds the discipline of life Lodges among the wise.",
        "32": "Those who spurn discipline hate themselves; But those who heed reproof gain understanding.",
        "33": "The fear of God is the discipline of wisdom; Humility precedes honor."
    },
    16: {
        "1": "Mortals may arrange their thoughts, But what they say depends on God.",
        "2": "People look approvingly on their own ways, But God probes motives.",
        "3": "Entrust your affairs to God, And your plans will succeed.",
        "4": "God made everything for a purpose, Even the wicked for an evil day.",
        "5": "Everyone haughty is an abomination to God; Assuredly, they will not go unpunished.",
        "6": "Iniquity is expiated by loyalty and faithfulness, And evil is avoided through fear of God.",
        "7": "God, when pleased with someone’s conduct, May turn even their enemies into allies.",
        "8": "Better a little with righteousness Than a large income with injustice.",
        "9": "Mortals may plot out their course, But it is God who directs their steps.",
        "10": "There is magic on the lips of the king; He cannot err in judgment.",
        "11": "Honest scales and balances are God’s, Whose work includes all the weights in the bag.",
        "12": "Wicked deeds are an abomination to kings, For the throne is established by righteousness.",
        "13": "Truthful speech wins the favor of kings; They love those who speak honestly.",
        "14": "The king’s wrath is a messenger of death, But a man who is wise can appease it.",
        "15": "The king’s smile means life; His favor is like a rain cloud in spring.",
        "16": "How much better to acquire wisdom than gold; To acquire understanding is preferable to silver.",
        "17": "The highway of the upright avoids evil; Those who would preserve their lives watch their way.",
        "18": "Pride goes before ruin, Arrogance, before failure.",
        "19": "Better to be humble and among the lowly Than to share spoils with the proud.",
        "20": "One who is adept in a matter will attain success; Happy is the one who trusts in God.",
        "21": "The wise-hearted are called discerning; Those whose speech is pleasing gain wisdom.",
        "22": "Good sense is a fountain of life to those who have it, And folly is the punishment of fools.",
        "23": "The mind of the wise makes their speech effective And increases the wisdom on their lips.",
        "24": "Pleasant words are like a honeycomb, Sweet to the palate and a cure for the body.",
        "25": "The road ahead may seem right, But in the end it can be a road to death.",
        "26": "The appetite of laborers labors for them, Because their hunger forces them on.",
        "27": "A worthless man plots evil; What is on his lips is like a scorching fire.",
        "28": "A shifty man stirs up strife, And a querulous one alienates his friend.",
        "29": "A lawless man misleads his friend, Making him take the wrong way.",
        "30": "He closes his eyes while meditating deception; He purses his lips while deciding upon evil.",
        "31": "Gray hair is a crown of glory; It is attained by the way of righteousness.",
        "32": "Better to be forbearing than mighty, To have self-control than to conquer a city.",
        "33": "Lots are cast into the lap; The decision depends on God."
    },
    17: {
        "1": "Better a dry crust with peace Than a house full of feasting with strife.",
        "2": "A capable servant will dominate an incompetent son And share the inheritance with the brothers.",
        "3": "For silver—the crucible, For gold—the furnace, And God tests the mind.",
        "4": "An evildoer listens to mischievous talk; A liar gives ear to malicious words.",
        "5": "One who mocks the poor affronts their Maker; One who rejoices over another’s misfortune will not go unpunished.",
        "6": "Grandchildren are the crown of their elders, And the glory of children is their parents.",
        "7": "Lofty words are not fitting for a villain, Much less lying words for a noble.",
        "8": "A bribe seems like a charm to its user; It brings success at every turn.",
        "9": "One who seeks love overlooks faults, But one who harps on a matter alienates friends.",
        "10": "A rebuke works on an intelligent person More than one hundred blows on a fool.",
        "11": "Evildoers seek only to rebel; A ruthless messenger will be sent against them.",
        "12": "Sooner meet a bereaved she-bear Than a fool immersed in nonsense.",
        "13": "Evil will never depart from the house Of one who repays good with evil.",
        "14": "To start a quarrel is to open a sluice; Before a dispute flares up, drop it.",
        "15": "To acquit the guilty and convict the innocent— Both are an abomination to God.",
        "16": "What good is money in the hand of a fool To purchase wisdom, when that person has no mind?",
        "17": "A friend is devoted at all times; A sibling is born to share adversity.",
        "18": "Devoid of sense are the people who give their hand To stand surety for their fellows.",
        "19": "One who loves transgression loves strife; One who builds a high threshold invites broken bones.",
        "20": "Crooked minds come to no good, And the double-tongued fall into trouble.",
        "21": "One begets a dullard to one’s own grief; The father of a villain has no joy.",
        "22": "A joyful heart makes for good health; Despondency dries up the bones.",
        "23": "The wicked draw bribes out of their bosom To pervert the course of justice.",
        "24": "Wisdom lies before the intelligent; The eyes of dullards range to the ends of the earth.",
        "25": "A stupid son is vexation for his father And a heartache for the woman who bore him.",
        "26": "To punish an innocent is surely not right, Or to flog the great for their uprightness.",
        "27": "One who is knowledgeable is sparing with words; A man of understanding is reticent.",
        "28": "Even fools who keep silent are deemed wise; Intelligent, while their mouth is shut."
    },
    18: {
        "1": "Those who isolate themselves pursue their desires; They disdain all competence.",
        "2": "Fools do not desire understanding, But only to air their thoughts.",
        "3": "Along with the wicked comes derision, And with rogues, contempt.",
        "4": "The words a person speaks are deep waters, A flowing stream, a fountain of wisdom.",
        "5": "It is not right to be partial to the guilty And subvert the innocent in judgment.",
        "6": "The words of fools lead to strife; Their speech invites blows.",
        "7": "The fools’ speech is their ruin; Their words are a trap for them.",
        "8": "The words of a grumbler are bruising; They penetrate one’s inmost parts.",
        "9": "One who is slack at work Is akin to a vandal.",
        "10": "God’s name is a tower of strength To which the righteous run and are safe.",
        "11": "The wealth of the rich is their fortress; In their fancy it is a protective wall.",
        "12": "Before ruin a person’s heart is proud; Humility goes before honor.",
        "13": "To answer before listening— This is foolish and disgraceful.",
        "14": "A person’s spirit can endure an illness; But low spirits—who can bear them?",
        "15": "The mind of an intelligent person acquires knowledge; The ears of the wise seek out knowledge.",
        "16": "A gift eases a person’s way And gives access to the great.",
        "17": "The first to speak in court seems right Till the other party cross-examines.",
        "18": "The lot puts an end to strife And separates those locked in dispute.",
        "19": "A sibling offended is more formidable than a stronghold; Such strife is like the bars of a fortress.",
        "20": "A man’s belly is filled by the fruit of his mouth; He will be filled by the produce of his lips.",
        "21": "Death and life are in the power of the tongue; Those who love it will eat its fruit.",
        "22": "He who finds a wife has found happiness And has won God’s favor.",
        "23": "The pauper speaks in terms of mercy; The rich person’s answer is harsh.",
        "24": "There are companions to keep one company, And there is a friend more devoted than a sibling."
    },
    19: {
        "1": "Better a pauper who lives blamelessly Than one who speaks perversely and is a dullard.",
        "2": "A person without knowledge is surely not good; One who moves hurriedly blunders.",
        "3": "Mortals’ folly subverts their way, And their hearts rage against God.",
        "4": "Wealth makes many friends, But a pauper is left friendless.",
        "5": "A false witness will not go unpunished; One who testifies lies will not escape.",
        "6": "Many court the favor of a noble, And all are the friends of a man who dispenses gifts.",
        "7": "The poor are despised even by their kin; How much more are they shunned by their friends! One who pursues words—they are of no avail.",
        "8": "Those who acquire wisdom are their own best friend; They preserve understanding and attain happiness.",
        "9": "A false witness will not go unpunished; One who testifies falsely is doomed.",
        "10": "Luxury is not fitting for a dullard, Much less that a servant rule over princes.",
        "11": "People show intelligence by their forbearance; It is their glory when they overlook an offense.",
        "12": "The rage of a king is like the roar of a lion; His favor is like dew upon the grass.",
        "13": "A stupid son is a calamity to his father; The nagging of a wife is like the endless dripping of water.",
        "14": "Property and riches are bequeathed by fathers, But an efficient wife comes from God.",
        "15": "Laziness induces sleep, And a negligent person will go hungry.",
        "16": "Those who have regard for their lives pay regard to commandments; Those who are heedless of their ways will die.",
        "17": "Those who are generous to the poor make a loan to God— They will receive their due.",
        "18": "Discipline your son while there is still hope, And do not set your heart on his destruction.",
        "19": "A hot-tempered man incurs punishment; If you try to save him you will only make it worse.",
        "20": "Listen to advice and accept discipline In order that you may be wise in the end.",
        "21": "Many designs are in a person’s mind, But it is God’s plan that is accomplished.",
        "22": "Greed is a reproach to a man; Better be poor than a deceitful man.",
        "23": "One who fears God earns life, And shall abide in contentment, Free from misfortune.",
        "24": "A sluggard buries a hand in the bowl, And will not even bring it to the mouth.",
        "25": "Beat scoffers and the simple will become clever; Reprove the intelligent and they gain knowledge.",
        "26": "A son who causes shame and disgrace Plunders his father, puts his mother to flight.",
        "27": "My son, cease to stray from words of knowledge And receive discipline.",
        "28": "A malicious witness scoffs at justice, And the speech of the wicked conceals mischief.",
        "29": "Punishments are in store for scoffers And blows for the backs of dullards."
    },
    20: {
        "1": "Wine is a scoffer, strong drink a roisterer; No one who is muddled by them will ever grow wise.",
        "2": "The terror of a king is like the roar of a lion; Whoever provokes it forfeits life.",
        "3": "It is honorable for a man to desist from strife, But every fool becomes embroiled.",
        "4": "In winter sluggards do not plow; At harvesttime they seek, and find nothing.",
        "5": "The designs in a person’s mind are deep waters, But a man of understanding can draw them out.",
        "6": "He calls many a man his loyal friend, But who can find a faithful man?",
        "7": "The righteous live blamelessly; Happy are their children who come after them.",
        "8": "The king seated on the throne of judgment Can winnow out all evil by his glance.",
        "9": "Who can say, 'I have cleansed my heart, I am purged of my sin'?",
        "10": "False weights and false measures— Both are an abomination to God.",
        "11": "Children may be dissembling in their behavior Even though their actions are blameless and proper.",
        "12": "The ear that hears, the eye that sees— God made them both.",
        "13": "Do not love sleep lest you be impoverished; Keep your eyes open and you will have plenty of food.",
        "14": "'Bad, bad,' says the buyer, Then goes away in self-congratulation.",
        "15": "Gold is plentiful, jewels abundant, But wise speech is a precious object.",
        "16": "Seize his garment, for he stood surety for another; Take it as a pledge, [for he stood surety] for an unfamiliar woman.",
        "17": "Bread gained by fraud may be tasty to a man, But later his mouth will be filled with gravel.",
        "18": "Plans laid in council will succeed; Wage war with stratagems.",
        "19": "Whoever gives away secrets is base; Do not take up with a big-mouth.",
        "20": "Whoever reviles their father or mother, Will be without lamplight when darkness comes.",
        "21": "An estate acquired in haste at the outset Will not be blessed in the end.",
        "22": "Do not say, 'I will requite evil'; Put your hope in God and you will be delivered.",
        "23": "False weights are an abomination to God; Dishonest scales are not right.",
        "24": "People’s steps are decided by God; What do mortals know about their own way?",
        "25": "It is a snare for mortals to pledge a sacred gift rashly And after the vows to reconsider.",
        "26": "A wise king winnows out the wicked, And turns the wheel upon them.",
        "27": "A mortal’s lifebreath is God’s lamp Revealing all their inmost parts.",
        "28": "Faithfulness and loyalty protect the king; He maintains his throne by faithfulness.",
        "29": "The glory of young men is their strength; The majesty of elders is their gray hair.",
        "30": "Bruises and wounds are repayment for evil, Striking at one’s inmost parts."
    },
    21: {
        "1": "Like channeled water is the mind of the king in God’s hand— For it is directed according to God’s wishes.",
        "2": "People look approvingly on their own ways, But God probes the mind.",
        "3": "To do what is right and just Is more desired by God than sacrifice.",
        "4": "Haughty looks, a proud heart— The tillage of the wicked is sinful.",
        "5": "The plans of the diligent make only for gain; All rash haste makes only for loss.",
        "6": "Treasures acquired by a lying tongue Are like driven vapor, heading for extinction.",
        "7": "The violence of the wicked sweeps them away, For they refuse to act justly.",
        "8": "A person’s way may be tortuous and strange, Though their actions are blameless and proper.",
        "9": "Dwelling in the corner of a roof is better Than a contentious wife in a spacious house.",
        "10": "The desire of the wicked is set upon evil; Their neighbors find no favor in their eyes.",
        "11": "When scoffers are punished, the simple are edified; When sages are taught, they gain insight.",
        "12": "The Righteous One observes the house of a wicked person— And subverts the wicked to their ruin.",
        "13": "One who turns a deaf ear to the cry of the wretched Will likewise call and not be answered.",
        "14": "A gift in secret subdues anger, A present in private, fierce rage.",
        "15": "Justice done is a joy to the righteous, To evildoers, ruination.",
        "16": "One who strays from the path of prudence Will rest in the company of ghosts.",
        "17": "A man who loves pleasure comes to want; He who loves wine and oil does not grow rich.",
        "18": "The wicked are the ransom of the righteous; The traitor comes in place of the upright.",
        "19": "It is better to live in the desert Than with a contentious, vexatious wife.",
        "20": "Precious treasure and oil are in the house of a wise man, And a fool of a man will run through them.",
        "21": "One who strives to do good and kind deeds Attains life, success, and honor.",
        "22": "One wise man prevailed over a city of warriors And brought down its mighty stronghold.",
        "23": "One who watches over mouth and tongue Keeps out of trouble.",
        "24": "The proud, insolent person, named scoffer, Acts in a frenzy of insolence.",
        "25": "The cravings of sluggards are fatal, For their hands refuse to work.",
        "26": "All day long they are seized with craving While the righteous give without stint.",
        "27": "The sacrifice of the wicked is an abomination, The more so when offered in depravity.",
        "28": "A false witness is doomed, But a man who listens will testify with success.",
        "29": "The wicked man is brazen-faced; The upright man discerns his course.",
        "30": "No wisdom, no prudence, and no counsel Can prevail against God.",
        "31": "The horse is readied for the day of battle, But victory comes from God."
    },
    22: {
        "1": "Repute is preferable to great wealth, Grace is better than silver and gold.",
        "2": "The rich and the poor meet; God made them both.",
        "3": "One who was shrewd saw trouble and took cover; The simple kept going and paid the penalty.",
        "4": "The effect of humility is fear of God, Wealth, honor, and life.",
        "5": "Thorns and snares are in the path of the crooked; Those who value their life will keep far from them.",
        "6": "Train children in the way they each ought to go; They will not swerve from it even in old age.",
        "7": "A rich person rules the poor, And the borrower is a slave to the man who lends.",
        "8": "One who sows injustice shall reap misfortune; The rod of wrath shall fail.",
        "9": "One who is generous is blessed, While giving bread to the poor.",
        "10": "Expel the scoffer and contention departs, Quarrel and contumely cease.",
        "11": "A pure-hearted comrade— His speech is gracious; He has the king for his companion.",
        "12": "The eyes of God watch the person who is wise; God subverts the words of the treacherous.",
        "13": "The sluggard says, 'There’s a lion in the street; I shall be killed if I step outside.'",
        "14": "The mouth of a forbidden woman is a deep pit; He who is doomed by God falls into it.",
        "15": "If folly settles in the heart of a youth, The rod of discipline will remove it.",
        "16": "To profit by withholding what is due to the poor Is like making gifts to the rich—pure loss.",
        "17": "Incline your ear and listen to the words of the sages; Pay attention to my wisdom.",
        "18": "It is good that you store them inside you, And that all of them be constantly on your lips,",
        "19": "That you may put your trust in God. I let you know today—yes, you—",
        "20": "Indeed, I wrote down for you a threefold lore, Wise counsel,",
        "21": "To let you know truly reliable words, That you may give a faithful reply to those who sent you.",
        "22": "Do not rob the wretched because they are wretched; Do not crush the poor in the gate;",
        "23": "For God will take up their cause And despoil those who despoil them of life.",
        "24": "Do not associate with a hothead, Or go about with a hot-tempered man,",
        "25": "Lest you learn their ways And find yourself ensnared.",
        "26": "Do not be one of those who give their hand, Who stand surety for debts,",
        "27": "Lest your bed be taken from under you When you have no money to pay.",
        "28": "Do not remove the ancient boundary stone That your ancestors set up.",
        "29": "See a man skilled at his work— He shall attend upon kings; He shall not attend upon the lowly."
    },
    23: {
        "1": "When you sit down to dine with a ruler, Consider well who is before you.",
        "2": "Thrust a knife into your gullet If you have a large appetite.",
        "3": "Do not crave the dainties, For they are counterfeit food.",
        "4": "Do not toil to gain wealth; Have the sense to desist.",
        "5": "You see it, then it is gone; It grows wings and flies away, Like an eagle, heavenward.",
        "6": "Do not eat of a miser’s food; Do not crave for his dainties;",
        "7": "He is like one keeping accounts; 'Eat and drink,' he says to you, But he does not really mean it.",
        "8": "The morsel you eat you will vomit; You will waste your courteous words.",
        "9": "Do not speak to a dullard— Who will disdain your sensible words.",
        "10": "Do not remove ancient boundary stones; Do not encroach upon the field of orphans,",
        "11": "For they have a mighty Redeemer, Who will surely take up their cause with you.",
        "12": "Apply your mind to discipline And your ears to wise sayings.",
        "13": "Do not withhold discipline from children; If you beat them with a rod they will not die.",
        "14": "Beat them with a rod And you will save them from the grave.",
        "15": "My son, if your mind gets wisdom, My mind, too, will be gladdened.",
        "16": "I shall rejoice with all my heart When your lips speak right things.",
        "17": "Do not envy sinners in your heart, But only those who fear God, at all times,",
        "18": "For then you will have a future, And your hope will never fail.",
        "19": "Listen, my son, and get wisdom; Lead your mind in a [proper] path.",
        "20": "Do not be of those who guzzle wine, Or glut themselves on meat,",
        "21": "For guzzlers and gluttons will be impoverished, And drowsing will clothe you in tatters.",
        "22": "Listen to your father who begot you; Do not disdain your mother when she is old.",
        "23": "Buy truth and never sell it, And wisdom, discipline, and understanding.",
        "24": "The father of a righteous person will exult; He who begets a wise child will rejoice in them.",
        "25": "Your father and mother will rejoice; She who bore you will exult.",
        "26": "Give your mind to me, my son; Let your eyes watch my ways.",
        "27": "A prostitute is a deep pit; A forbidden woman is a narrow well.",
        "28": "She too lies in wait as if for prey, And destroys the unfaithful among men.",
        "29": "Who cries, 'Woe!' who, 'Alas!'; Who has quarrels, who complaints; Who has wounds without cause; Who has bleary eyes?",
        "30": "Those whom wine keeps till the small hours, Those who gather to drain the cups.",
        "31": "Do not ogle that red wine As it lends its color to the cup, As it flows on smoothly;",
        "32": "In the end, it bites like a snake; It spits like a basilisk.",
        "33": "Your eyes will see strange sights; Your heart will speak distorted things.",
        "34": "You will be like one lying in bed on high seas, Like one lying on top of the rigging.",
        "35": "'They struck me, but I felt no hurt; They beat me, but I was unaware; As often as I wake, I go after it again.'"
    },
    24: {
        "1": "Do not envy the wicked; Do not desire to be with them;",
        "2": "For their hearts talk violence, And their lips speak mischief.",
        "3": "A house is built by wisdom, And is established by understanding;",
        "4": "By knowledge are its rooms filled With all precious and beautiful things.",
        "5": "A wise man is strength; A knowledgeable man exerts power;",
        "6": "For by stratagems you wage war, And victory comes with much planning.",
        "7": "Wisdom is too lofty for an ignoramus; He does not open his mouth in the gate.",
        "8": "One who lays plans to do harm Is called a schemer.",
        "9": "The schemes of folly are sin, And a scoffer is an abomination to all.",
        "10": "If you showed yourself slack in time of trouble, Wanting in power,",
        "11": "If you refrained from rescuing those taken off to death, Those condemned to slaughter—",
        "12": "If you say, 'We knew nothing of it,' Surely the One who fathoms hearts will discern [the truth], The One who watches over your life will know it, And [God] will pay each person as they deserve.",
        "13": "My son, eat honey, for it is good; Let its sweet drops be on your palate.",
        "14": "Know: such is wisdom for your soul; If you attain it, there is a future; Your hope will not be cut off.",
        "15": "Wicked ones! Do not lurk by the home of the righteous; Do no violence to their dwellings.",
        "16": "Seven times a righteous person falls and gets up, While the wicked are tripped by one misfortune.",
        "17": "If your enemies fall, do not exult; If they trip, let your heart not rejoice,",
        "18": "Lest God see it and be displeased, And avert God’s wrath from them.",
        "19": "Do not be vexed by evildoers; Do not be incensed by the wicked;",
        "20": "For there is no future for an evildoer; The lamp of the wicked goes out.",
        "21": "Fear God, my son, and the king, And do not mix with dissenters,",
        "22": "For disaster comes from them suddenly; The doom both decree who can foreknow?",
        "23": "These also are by the sages: It is not right to be partial in judgment.",
        "24": "One who says to the guilty, 'You are innocent,' Shall be cursed by peoples, Damned by nations;",
        "25": "But it shall go well with them who decide justly; Blessings of good things will light upon them.",
        "26": "Giving a straightforward reply Is like giving a kiss.",
        "27": "Put your external affairs in order, Get ready what you have in the field, Then build yourself a home.",
        "28": "Do not be a witness against your fellow without good cause; Would you mislead with your speech?",
        "29": "Do not say, 'I will do to him what he did to me; I will pay the man what he deserves.'",
        "30": "I passed by the field of a lazy man, By the vineyard of someone lacking sense.",
        "31": "It was all overgrown with thorns; Its surface was covered with chickweed, And its stone fence lay in ruins.",
        "32": "I observed and took it to heart; I saw it and learned a lesson.",
        "33": "A bit more sleep, a bit more slumber, A bit more hugging yourself in bed,",
        "34": "And poverty will come calling upon you, And want, like a man with a shield."
    },
    25: {
        "1": "These too are proverbs of Solomon, which the officials of King Hezekiah of Judah copied:",
        "2": "It is the glory of God to conceal a matter, And the glory of a king to plumb a matter.",
        "3": "Like the heavens in their height, like the earth in its depth, Is the mind of kings—unfathomable.",
        "4": "The dross having been separated from the silver, A vessel emerged for the smith.",
        "5": "Remove the wicked from the king’s presence, And his throne will be established in justice.",
        "6": "Do not exalt yourself in the king’s presence; Do not stand in the place of nobles.",
        "7": "For it is better to be told, 'Step up here,' Than to be degraded in the presence of the great. Do not let what your eyes have seen",
        "8": "Be vented rashly in a quarrel; Think of what it will effect in the end, When your fellow puts you to shame.",
        "9": "Defend your right against your fellow, But do not give away the secrets of another,",
        "10": "Lest someone who hears it reproach you, And your bad repute never end.",
        "11": "Like golden apples in silver showpieces Is a phrase well turned.",
        "12": "Like a ring of gold, a golden ornament, Is a wise person’s reproof in a receptive ear.",
        "13": "Like the coldness of snow at harvesttime Is a trustworthy messenger to those who send him; He lifts his master’s spirits.",
        "14": "Like clouds, wind—but no rain— Is a man who boasts of gifts not given.",
        "15": "Through forbearance a ruler may be won over; A gentle tongue can break bones.",
        "16": "If you find honey, eat only what you need, Lest, surfeiting yourself, you throw it up.",
        "17": "Visit your neighbor sparingly, Lest he have his surfeit of you and loathe you.",
        "18": "Like a club, a sword, a sharpened arrow, Is a man who testifies falsely against his fellow.",
        "19": "Like a loose tooth and an unsteady leg, Is a treacherous support in time of trouble.",
        "20": "Disrobing on a chilly day, Like vinegar on natron, Is one who sings songs to a sorrowful soul.",
        "21": "If your enemy is hungry, give him bread to eat; If he is thirsty, give him water to drink.",
        "22": "You will be heaping live coals on his head, And God will reward you.",
        "23": "A north wind produces rain, And whispered words, a glowering face.",
        "24": "Dwelling in the corner of a roof is better Than a contentious woman in a spacious house.",
        "25": "Like cold water to a parched throat Is good news from a distant land.",
        "26": "Like a muddied spring, a ruined fountain, Are the righteous fallen before the wicked.",
        "27": "It is not good to eat much honey, Nor is it honorable to search for honor.",
        "28": "Like an open city without walls Is a man whose temper is uncurbed."
    },
    26: {
        "1": "Like snow in summer and rain at harvesttime, So honor is not fitting for a dullard.",
        "2": "As a sparrow must flit and a swallow fly, So a gratuitous curse must backfire.",
        "3": "A whip for a horse and a bridle for a donkey, And a rod for the back of dullards.",
        "4": "Do not answer a dullard in accord with his folly, Else you will become like him.",
        "5": "Answer a dullard in accord with his folly, Else he will think himself wise.",
        "6": "One who sends a message by a dullard Will wear out legs and must put up with lawlessness.",
        "7": "As legs hang limp on a cripple, So is a proverb in the mouth of dullards.",
        "8": "Like a pebble in a sling, So is paying honor to a dullard.",
        "9": "As a thorn comes to the hand of a drunkard, So a proverb to the mouth of a dullard.",
        "10": "A master can produce anything, But anyone who hires a dullard is as one who hires transients.",
        "11": "As a dog returns to its vomit, So a dullard repeats his folly.",
        "12": "If you see a man who thinks himself wise, There is more hope for a dullard than for him.",
        "13": "The sluggard says, 'There’s a cub on the road, a lion in the squares.'",
        "14": "The door turns upon the hinge, And the sluggard upon the bed.",
        "15": "The sluggard buries a hand in the bowl, And will not even bring it to the mouth.",
        "16": "In self-regard, the sluggard is wiser Than seven who give good advice.",
        "17": "A passerby who gets embroiled in someone else’s quarrel Is like one who seizes a dog by its ears.",
        "18": "Like a lunatic scattering deadly firebrands, arrows,",
        "19": "Is the man who cheats his fellow and says, 'I was only joking.'",
        "20": "For lack of wood a fire goes out, And without a grumbler contention is stilled.",
        "21": "Charcoal for embers and wood for a fire And a contentious man for kindling strife.",
        "22": "The words of a grumbler are bruising; They penetrate one’s inmost parts.",
        "23": "Base silver laid over earthenware Are ardent lips with an evil mind.",
        "24": "An enemy dissembles with his speech, Inwardly he harbors deceit.",
        "25": "Though he be fair-spoken do not trust him, For seven abominations are in his mind.",
        "26": "His hatred may be concealed by dissimulation, But his evil will be exposed to public view.",
        "27": "One who digs a pit will fall in it, And a stone will roll back upon the one who is rolling it.",
        "28": "A lying tongue hates those crushed by it; Smooth speech throws one down."
    },
    27: {
        "1": "Do not boast of tomorrow, For you do not know what the day will bring.",
        "2": "Let the mouth of another praise you, not yours, The lips of a stranger, not your own.",
        "3": "A stone has weight, sand is heavy, But a fool’s vexation outweighs them both.",
        "4": "There is the cruelty of fury, the overflowing of anger, But who can withstand jealousy?",
        "5": "Open reproof is better than concealed love.",
        "6": "Wounds by a loved one are long lasting; The kisses of an enemy are profuse.",
        "7": "A sated appetite disdains honey, But to a ravenous appetite, even the bitter is sweet.",
        "8": "Like a sparrow wandering from its nest Is a man who wanders from his home.",
        "9": "Oil and incense gladden the heart, And the sweetness of a friend is better than one’s own counsel.",
        "10": "Do not desert your friend and your father’s friend; Do not enter your brother’s house in your time of misfortune; A close neighbor is better than a distant brother.",
        "11": "Get wisdom, my son, and gladden my heart, That I may have what to answer those who taunt me.",
        "12": "The shrewd man saw trouble and took cover; The simple kept going and paid the penalty.",
        "13": "Seize his garment, for he stood surety for another; Take it as a pledge, [for he stood surety] for an unfamiliar woman.",
        "14": "He who greets his fellow loudly early in the morning Shall have it reckoned to him as a curse.",
        "15": "An endless dripping on a rainy day And a contentious wife are alike;",
        "16": "As soon repress her as repress the wind, Or declare one’s right hand to be oil.",
        "17": "As iron sharpens iron So a man sharpens the wit of his friend.",
        "18": "One who tends a fig tree will enjoy its fruit, And one who cares for a master will be honored.",
        "19": "As face answers to face in water, So does one’s heart to another’s.",
        "20": "Sheol and Abaddon cannot be satisfied, Nor can the human eye be satisfied.",
        "21": "For silver—the crucible, for gold—the furnace, And a person is tested by praise.",
        "22": "Even if you pound the fool in a mortar With a pestle along with grain, His folly will not leave him.",
        "23": "Mind well the looks of your flock; Pay attention to your herds;",
        "24": "For property does not last forever, Or a crown for all generations.",
        "25": "Grass vanishes, new grass appears, And the herbage of the hills is gathered in.",
        "26": "The lambs will provide you with clothing, The he-goats, the price of a field.",
        "27": "The goats’ milk will suffice for your food, The food of your household, And the maintenance of your maids."
    },
    28: {
        "1": "A wicked person flees though no one gives chase, But the righteous are as confident as a lion.",
        "2": "When there is rebellion in the land, many are its rulers; But with someone who has understanding and knowledge, stability will last.",
        "3": "A poor man who withholds what is due to the wretched Is like a destructive rain that leaves no food.",
        "4": "Those who forsake instruction praise the wicked, But those who heed instruction fight them.",
        "5": "The wicked cannot discern judgment, But those who seek God discern all things.",
        "6": "Better is a poor man who lives blamelessly Than a rich man whose ways are crooked.",
        "7": "An intelligent son heeds instruction, But he who keeps company with gluttons disgraces his father.",
        "8": "He who increases his wealth by loans at discount or interest Amasses it for one who is generous to the poor.",
        "9": "He who turns a deaf ear to instruction— His prayer is an abomination.",
        "10": "He who misleads the upright into an evil course Will fall into his own pit, But the blameless will prosper.",
        "11": "A rich man is clever in his own eyes, But a perceptive pauper can see through him.",
        "12": "When the righteous exult there is great glory, But when the wicked rise up, everyone makes themselves scarce.",
        "13": "No one who covers up faults will succeed; One who confesses and gives them up will find mercy.",
        "14": "Happy is the person who is anxious always, But one who is hard-hearted falls into misfortune.",
        "15": "A roaring lion and a prowling bear Is a wicked man ruling a helpless people.",
        "16": "A prince who lacks understanding is very oppressive; One who spurns ill-gotten gains will live long.",
        "17": "Anyone oppressed by bloodguilt will flee to a pit; Let none offer support.",
        "18": "One who lives blamelessly will be delivered, But one whose ways are crooked will fall all at once.",
        "19": "Those who till their land will have food in plenty, But those who pursue vanities will have poverty in plenty.",
        "20": "A dependable man will receive many blessings, But one in a hurry to get rich will not go unpunished.",
        "21": "To be partial is not right; Even one who is valiant may do wrong for a piece of bread.",
        "22": "A miserly man runs after wealth; He does not realize that loss will overtake it.",
        "23": "One who reproves a person will in the end Find more favor than a flatterer.",
        "24": "Anyone who robs their father and mother and says, 'It is no offense,' Is the companion to a vandal.",
        "25": "A gaping maw provokes quarrels, But one who trusts God shall enjoy prosperity.",
        "26": "Those who trust their own instincts are dullards, But those who live by wisdom shall escape.",
        "27": "Those who give to the poor will not be in want, But those who turn a blind eye will be roundly cursed.",
        "28": "When the wicked rise up, everyone goes into hiding, But when they perish the righteous increase."
    },
    29: {
        "1": "One oft reproved may become stiffnecked— But then will be suddenly broken beyond repair.",
        "2": "When the righteous become great the people rejoice, But when the wicked dominate the people groan.",
        "3": "A man who loves wisdom brings joy to his father, But he who keeps company with prostitutes will lose his wealth.",
        "4": "By justice a king sustains the land, But a fraudulent man tears it down.",
        "5": "A man who flatters his fellow Spreads a net for his feet.",
        "6": "An evil man’s offenses are a trap for himself, But a righteous person sings out joyously.",
        "7": "The righteous are concerned with the cause of the wretched; The wicked cannot understand such concern.",
        "8": "Scoffers inflame a city, But the wise allay anger.",
        "9": "When someone who is wise enters into litigation with a fool There is ranting and ridicule, but no satisfaction.",
        "10": "Those who are bloodthirsty detest the blameless, But the upright seek them out.",
        "11": "A dullard gives full vent to rage, But a wise person calms it down.",
        "12": "A ruler who listens to lies— All his ministers will be wicked.",
        "13": "The poor and the fraudulent meet; God gives luster to the eyes of both.",
        "14": "A king who judges the wretched honestly— His throne will be established forever.",
        "15": "Rod and reproof produce wisdom, But a youth out of control is a disgrace to his mother.",
        "16": "When the wicked increase, offenses increase, But the righteous will see their downfall.",
        "17": "Discipline your son and he will give you peace; He will gratify you with dainties.",
        "18": "For lack of vision a people lose restraint, But happy is he who heeds instruction.",
        "19": "A slave cannot be disciplined by words; Though he may comprehend, he does not respond.",
        "20": "If you see a man hasty in speech, There is more hope for a fool than for him.",
        "21": "A slave pampered from youth Will come to a bad end.",
        "22": "An angry man provokes a quarrel; A hothead commits many offenses.",
        "23": "Pride of mortals will bring humiliation, But one who is humble will obtain honor.",
        "24": "He who shares with a thief is his own enemy; He hears the imprecation and does not tell.",
        "25": "A person’s fears become a trap, But one who trusts in God shall be safeguarded.",
        "26": "Many seek audience with a ruler, But it is from God that a [wronged] party gets justice.",
        "27": "The unjust man is an abomination to the righteous, And one whose way is straight is an abomination to the wicked."
    },
    30: {
    "1": "The words of Agur son of Jakeh, [man of] Massa; the speech of the man to Ithiel, to Ithiel and Ucal:",
    "2": "I am more brutish than anyone else; I lack common sense.",
    "3": "I have not learned wisdom, Nor do I possess knowledge of the Holy One.",
    "4": "Who has ascended heaven and come down? Who has gathered up the wind in the hollow of his hand? Who has wrapped the waters in his garment? Who has established all the extremities of the earth? What is his name or his son’s name, if you know it?",
    "5": "Every word of God is pure, A shield to those who seek refuge.",
    "6": "Do not add to God’s words, Lest you be indicted and proved to be a liar.",
    "7": "Two things I ask of You; do not deny them to me before I die:",
    "8": "Keep lies and false words far from me; Give me neither poverty nor riches, But provide me with my daily bread,",
    "9": "Lest, being sated, I renounce, saying, 'Who is God?' Or, being impoverished, I take to theft And profane the name of my God.",
    "10": "Do not inform on a slave to his master, Lest he curse you and you incur guilt.",
    "11": "There is a breed of people that brings a curse on its fathers And brings no blessing to its mothers,",
    "12": "A breed that thinks itself pure, Though it is not washed of its filth;",
    "13": "A breed so haughty of bearing, so supercilious;",
    "14": "A breed whose teeth are swords, Whose jaws are knives, Ready to devour the poor of the land, The needy among us.",
    "15": "The leech has two daughters, 'Give!' and 'Give!' Three things are insatiable; Four never say, 'Enough!':",
    "16": "Sheol, an infertile womb, Earth that cannot get enough water, And fire that never says, 'Enough!'",
    "17": "The eye that mocks a father And disdains the homage due a mother— The ravens of the brook will gouge it out, Young eagles will devour it.",
    "18": "Three things are beyond me; Four I cannot fathom:",
    "19": "How an eagle makes its way over the sky; How a snake makes its way over a rock; How a ship makes its way through the high seas; How a man has his way with a maiden.",
    "20": "Such is the way of an adulteress: She eats, wipes her mouth, And says, 'I have done no wrong.'",
    "21": "The earth shudders at three things, At four that it cannot bear:",
    "22": "A slave who becomes king; A scoundrel sated with food;",
    "23": "A loathsome woman who gets married; A maidservant who supplants her mistress.",
    "24": "Four are among the tiniest on earth, Yet they are the wisest of the wise:",
    "25": "Ants are a folk without power, Yet they prepare food for themselves in summer;",
    "26": "The badger is a folk without strength, Yet it makes its home in the rock;",
    "27": "The locusts have no king, Yet they all march forth in formation;",
    "28": "You can catch the lizard in your hand, Yet it is found in royal palaces.",
    "29": "There are three that are stately of stride, Four that carry themselves well:",
    "30": "The lion is mightiest among the beasts, And recoils before none;",
    "31": "The greyhound, the he-goat, The king whom none dares resist.",
    "32": "If you have been scandalously arrogant, If you have been a schemer, Then clap your hand to your mouth.",
    "33": "As milk under pressure produces butter, And a nose under pressure produces blood, So patience under pressure produces strife."
    },
    31: {
    "1": "The words of Lemuel, king of Massa, with which his mother admonished him:",
    "2": "No, my son! No, O son of my womb! No, O son of my vows!",
    "3": "Do not give your strength to women, Your vigor, to those who destroy kings.",
    "4": "Wine is not for kings, O Lemuel; Not for kings to drink, Nor any strong drink for princes,",
    "5": "Lest they drink and forget what has been ordained, And infringe on the rights of the poor.",
    "6": "Give strong drink to the hapless And wine to the embittered.",
    "7": "Let them drink and forget their poverty, And put their troubles out of mind.",
    "8": "Speak up for the dumb, For the rights of all the unfortunate.",
    "9": "Speak up, judge righteously, Champion the poor and the needy.",
    "10": "How precious is a woman of substance! Her worth is far beyond that of rubies.",
    "11": "Her husband puts his confidence in her, And lacks no good thing.",
    "12": "She is good to him, never bad, All the days of her life.",
    "13": "She looks for wool and flax, And sets her hand to them with a will.",
    "14": "She is like a merchant fleet, Bringing her food from afar.",
    "15": "She rises while it is still night, And supplies provisions for her household, The daily fare of her maids.",
    "16": "She sets her mind on an estate and acquires it; She plants a vineyard by her own labors.",
    "17": "She girds herself with strength, And performs her tasks with vigor.",
    "18": "She sees that her business thrives; Her lamp never goes out at night.",
    "19": "She sets her hand to the distaff; Her fingers work the spindle.",
    "20": "She gives generously to the poor; Her hands are stretched out to the needy.",
    "21": "She is not worried for her household because of snow, For her whole household is dressed in crimson.",
    "22": "She makes covers for herself; Her clothing is linen and purple.",
    "23": "Her husband is prominent in the gates, As he sits among the elders of the land.",
    "24": "She makes cloth and sells it, And offers a girdle to the merchant.",
    "25": "She is clothed with strength and splendor; She looks to the future cheerfully.",
    "26": "Her mouth is full of wisdom, Her tongue with kindly teaching.",
    "27": "She oversees the activities of her household And never eats the bread of idleness.",
    "28": "Her children declare her happy; Her husband praises her,",
    "29": "'Many women have done well, But you surpass them all.'",
    "30": "Grace is deceptive, Beauty is illusory; It is for her fear of God That a woman is to be praised.",
    "31": "Give her of the fruit of her hands, And let her works praise her in the gates."    
    },
}
